#ifndef REGISTERS_H
#define REGISTERS_H

#define WHOAMI_REG 0x75
#define GYRO_CONFIGURATION_REG 0x1B
#define PWR_MGMT_1_REG 0x6B
#define CONFIGURATION_REG 0x1A
#define INTR_ENABLE_REG 0x38
#define INTR_ENABLE_STATUS 0x3A
#define SMPRT_DIV_REG 0x19

#define GYRO_REG_XOUT_H 0x43
#define GYRO_REG_XOUT_L 0x44
#define GYRO_REG_YOUT_H 0x45
#define GYRO_REG_YOUT_L 0x46
#define GYRO_REG_ZOUT_H 0x47
#define GYRO_REG_ZOUT_L 0x48

#endif //! REGISTERS_H